language:
    - objective-c

script:
    - wget https://github.com/phonegap/ios-sim/archive/1.8.2.tar.gz
    - tar -xvf 1.8.2.tar.gz
    - cd ios-sim-1.8.2/
    - xcodebuild -target ios-sim
    - export PATH=`pwd`/build/Release:${PATH}
    - which ios-sim
    - ios-sim --version
